---

#----------------------------------------------------------------------------------------------------------
# This playbook is used to set up Centos 7 server and deploy Python Pyramid application with nginx and wsgi
#
# NOTE: commented parts do not work yet
#
#----------------------------------------------------------------------------------------------------------


- hosts: servers # {{ insert host or host group here }} 
  remote_user: root
  become: true
  gather_facts: yes

  vars:
    user: riddle
    ansible_become_pass: asdfjkl8gb

    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"

  tasks:

  - name: check if epel repo is already configured.
    stat: path={{ epel_repofile_path }}
    register: epel_repofile_result

  - name: Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    register: result
    until: '"failed" not in result'
    retries: 5
    delay: 10
    when: not epel_repofile_result.stat.exists

  - name: Import EPEL GPG key.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: not epel_repofile_result.stat.exists
    ignore_errors: "{{ ansible_check_mode }}"

  - name: upgrade all packages
    yum: name=* state=latest


  - name: install cowsay and ensure it is at the latest version 
    yum: name=cowsay state=latest

  - name: install the required environment package groups
    yum: name=@^{{item}} state=present
    with_items:
      - "Minimal Install"
      - "Basic Web Server"

  - name: install the required package groups
    yum: name=@{{item}} state=present
    with_items:
      - base
      - core
      - debugging
      - "system administration tools"
      - "security tools"
      - "virtualization"
      - "system management"
      - "development tools"

  - name: install additional packages
    yum: name={{item}} state=latest
    with_items:
      - nginx
      - firewalld
      - vim
      - git
      - telnet
      - mlocate
  - command: updatedb

  - name: set up nginx
    file: path=/etc/nginx/conf.d state=directory
  - template: src=/etc/ansible/templates/nginx.conf dest=/etc/nginx/conf.d/{{ project_name }}.conf
  - command: systemctl start nginx
  - command: systemctl enable nginx

